// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var detail, master;
    master = function(title) {
      return $.ajax({
        url: "http://www.omdbapi.com/?s=" + title
      }).done(function(data) {
        var movie, movies, _i, _len;
        movies = $.parseJSON(data)['Search'];
        console.log(movies);
        for (_i = 0, _len = movies.length; _i < _len; _i++) {
          movie = movies[_i];
          $('#movies').append("<li data-imdb=" + movie.imdbID + ">" + movie.Title + "</li>");
        }
        return $('li').on('click', function(e) {
          var imdbID;
          console.log(e.target);
          console.log($(e.target));
          imdbID = $(e.target).data('imdb');
          return detail(imdbID);
        });
      }).fail(function(j, t, e) {
        return console.log(j, t, e);
      });
    };
    master("Harry");
    return detail = function(imdbID) {
      return $.ajax({
        url: "http://www.omdbapi.com/?i=" + imdbID + "&tomatoes=true&plot=full"
      }).done(function(data) {
        var movie;
        console.log(data);
        movie = $.parseJSON(data);
        return $('#detail').html('<span>' + movie.Plot + '</span>');
      }).fail(function(j, t, e) {
        return console.log(j, t, e);
      });
    };
  });

}).call(this);
